export enum ReturnPickupStatus {
  SCHEDULED = 'SCHEDULED',
  ATTEMPTED = 'ATTEMPTED',
  PICKED_UP = 'PICKED_UP',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED_TO_WAREHOUSE = 'DELIVERED_TO_WAREHOUSE',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}
