// import * as Joi from 'joi';

// export const envValidationSchema = Joi.object({
//   NODE_ENV: Joi.string().valid('development', 'production', 'test', 'staging').default('development'),
//   PORT: Joi.number().default(3000),
//   DATABASE_URL: Joi.string().uri().required(),
//   REDIS_HOST: Joi.string().default('localhost'),
//   REDIS_PORT: Joi.number().default(6379),
//   REDIS_PASSWORD: Joi.string().allow('').optional(),
//   CACHE_TTL: Joi.number().default(300),
//   JWT_SECRET: Joi.string().min(32).required(),
//   JWT_EXPIRES_IN: Joi.string().default('7d'),
//   JWT_ACCESS_EXPIRES_IN: Joi.string().default('15m'),
//   JWT_REFRESH_EXPIRES_IN_DAYS: Joi.number().integer().min(1).max(365).default(90),
//   LOG_LEVEL: Joi.string().valid('fatal', 'error', 'warn', 'info', 'debug', 'trace').default('info'),
//   CORS_ORIGINS: Joi.string().optional(),
//   DATABASE_LOGGING: Joi.string().valid('true', 'false').optional(),
//   STORAGE_DRIVER: Joi.string().valid('local', 'gcs').default('local'),
//   UPLOAD_DIR: Joi.string().optional(),
//   UPLOAD_MAX_FILE_SIZE: Joi.number().default(5242880),
//   UPLOAD_ALLOWED_MIME_TYPES: Joi.string().optional(),
// });

import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string()
    .valid('development', 'production', 'test', 'staging', 'beta')
    .default('development'),
  PORT: Joi.number().default(3000),
  DATABASE_URL: Joi.string().uri().required(),
  REDIS_HOST: Joi.string().default('localhost'),
  REDIS_PORT: Joi.number().default(6379),
  REDIS_PASSWORD: Joi.string().allow('').optional(),
  REDIS_USERNAME: Joi.string().allow('').optional(),
  REDIS_TLS: Joi.string().valid('true', 'false').default('false'),
  CACHE_TTL: Joi.number().default(300),
  ATTRIBUTE_CACHE_TTL: Joi.number().default(300),
  BRAND_CACHE_TTL: Joi.number().default(300),
  CATEGORY_CACHE_TTL: Joi.number().default(600),
  PRODUCT_CACHE_TTL: Joi.number().default(900),
  HOMEPAGE_CACHE_TTL: Joi.number().default(600),
  SESSION_CACHE_TTL: Joi.number().default(300),
  OTP_RESEND_COOLDOWN_SECONDS: Joi.number().integer().min(30).max(300).default(60),
  OTP_MOBILE_MAX_REQUESTS: Joi.number().integer().min(1).max(50).default(5),
  OTP_IP_MAX_REQUESTS: Joi.number().integer().min(1).max(500).default(60),
  OTP_RATE_LIMIT_WINDOW_SECONDS: Joi.number().integer().min(60).max(3600).default(900),
  REDIS_CONNECT_TIMEOUT_MS: Joi.number().integer().min(500).default(5000),
  REDIS_OPERATION_TIMEOUT_MS: Joi.number().integer().min(500).default(8000),
  JWT_SECRET: Joi.string().min(32).required(),
  JWT_EXPIRES_IN: Joi.string().default('7d'),
  JWT_ACCESS_EXPIRES_IN: Joi.string().default('15m'),
  JWT_REFRESH_EXPIRES_IN_DAYS: Joi.number().integer().min(1).max(365).default(90),
  // Optional — LoggerModule resolves development→debug, production/staging/beta→info, test→silent
  LOG_LEVEL: Joi.string()
    .valid('fatal', 'error', 'warn', 'info', 'debug', 'trace', 'silent')
    .optional(),
  LOG_SERVICE_NAME: Joi.string().allow('').optional(),
  APP_ENV: Joi.string().allow('').optional(),
  CORS_ORIGINS: Joi.string().allow('').optional(),
  COOKIE_SECURE: Joi.string().valid('true', 'false').optional(),
  DATABASE_LOGGING: Joi.string().valid('true', 'false').optional(),
  STORAGE_DRIVER: Joi.string().valid('local', 'gcs').default('local'),
  UPLOAD_DIR: Joi.string().allow('').optional(),
  UPLOAD_MAX_IMAGE_FILE_SIZE: Joi.number().default(5242880),
  UPLOAD_MAX_VIDEO_FILE_SIZE: Joi.number().default(20971520),
  PRODUCT_BULK_UPLOAD_MAX_IMAGE_SIZE: Joi.number().integer().min(1048576).default(5242880),
  PRODUCT_BULK_UPLOAD_MAX_SHEET_SIZE: Joi.number().integer().min(1048576).default(41943040),
  PRODUCT_BULK_UPLOAD_LOCK_TTL_MS: Joi.number().integer().min(1200000).default(1800000),
  UPLOAD_MAX_MULTIPART_FILES: Joi.number().integer().min(1).max(200).default(50),
  UPLOAD_ALLOWED_MIME_TYPES: Joi.string().allow('').optional(),
  GCS_BUCKET_NAME: Joi.string().when('STORAGE_DRIVER', {
    is: 'gcs',
    then: Joi.required(),
    otherwise: Joi.allow('').optional(),
  }),
  GCS_CREDENTIALS_PATH: Joi.string().when('STORAGE_DRIVER', {
    is: 'gcs',
    then: Joi.required(),
    otherwise: Joi.allow('').optional(),
  }),
  GCS_SIGNED_URL_TTL_SECONDS: Joi.number().integer().min(60).max(604800).default(3600),
  IMAGE_DELIVERY_ENABLED: Joi.string().valid('true', 'false').default('false'),
  IMAGE_PROCESSING_ENABLED: Joi.string().valid('true', 'false').default('false'),
  IMAGE_WORKER_ENABLED: Joi.string().valid('true', 'false').default('false'),
  IMAGE_WORKER_CONCURRENCY: Joi.number().integer().min(1).max(4).default(1),
  IMAGE_PIPELINE_VERSION: Joi.string().max(32).default('v1'),
  IMAGE_DERIVATIVE_PREFIX: Joi.string().max(64).default('derivatives'),
  IMAGE_ALLOWED_WIDTHS: Joi.string().allow('').optional(),
  IMAGE_WEBP_QUALITY: Joi.number().integer().min(50).max(90).default(80),
  IMAGE_MAX_INPUT_BYTES: Joi.number().integer().min(1024).max(50 * 1024 * 1024).default(15 * 1024 * 1024),
  IMAGE_MAX_DECODED_PIXELS: Joi.number().integer().min(1_000_000).max(100_000_000).default(40_000_000),
  IMAGE_PROCESS_TIMEOUT_MS: Joi.number().integer().min(1000).max(120000).default(30000),
  IMAGE_RETRY_ATTEMPTS: Joi.number().integer().min(1).max(10).default(5),
  IMAGE_RETRY_BACKOFF_MS: Joi.number().integer().min(500).max(60000).default(5000),
  IMAGE_JOB_RETENTION_COMPLETE: Joi.number().integer().min(1).max(1000).default(100),
  IMAGE_JOB_RETENTION_FAILED: Joi.number().integer().min(1).max(1000).default(200),
  IMAGE_RECONCILE_INTERVAL_MS: Joi.number().integer().min(60000).max(3600000).default(300000),
  IMAGE_RECONCILE_BATCH_SIZE: Joi.number().integer().min(1).max(200).default(50),
  IMAGE_BACKFILL_BATCH_SIZE: Joi.number().integer().min(1).max(500).default(50),
  IMAGE_BACKFILL_RATE_LIMIT_MS: Joi.number().integer().min(0).max(10000).default(100),
  IMAGE_SIGNED_URL_TTL_SECONDS: Joi.number().integer().min(60).max(604800).optional(),
  // Unicommerce integration credentials — issued by Cureka to Unicommerce per seller
  UNICOMMERCE_USERNAME: Joi.string().allow('').optional(),
  UNICOMMERCE_PASSWORD: Joi.string().allow('').optional(),
  UNICOMMERCE_TENANT: Joi.string().allow('').optional(),
  UNICOMMERCE_CHANNEL: Joi.string().allow('').optional(),
  UNICOMMERCE_DEFAULT_FACILITY_CODE: Joi.string().allow('').optional(),
  UNICOMMERCE_DEFAULT_HSN_CODE: Joi.string().allow('').optional(),
  UNICOMMERCE_PRODUCT_BASE_URL: Joi.string().uri().allow('').optional(),
  // Outbound order push — Unicommerce official tenant API (OAuth 2.0)
  UNICOMMERCE_ORDER_PUSH_ENABLED: Joi.string().valid('true', 'false').optional(),
  UNICOMMERCE_ORDER_CURRENCY: Joi.string().allow('').optional(),
  UNICOMMERCE_ORDER_TIMEOUT_MS: Joi.number().integer().min(1000).allow('').optional(),
  UNICOMMERCE_PRODUCT_PUSH_ENABLED: Joi.string().valid('true', 'false').optional(),
  UNICOMMERCE_PRODUCT_PUSH_BASE_URL: Joi.string().uri().allow('').optional(),
  UNICOMMERCE_PRODUCT_PUSH_TIMEOUT_MS: Joi.number().integer().min(1000).allow('').optional(),
  UNICOMMERCE_CATEGORY_CODE: Joi.string().allow('').optional(),
  RAZORPAY_KEY_ID: Joi.string().allow('').optional(),
  RAZORPAY_SECRET: Joi.string().allow('').optional(),
  RAZORPAY_WEBHOOK_SECRET: Joi.string().allow('').optional(),
  RAZORPAY_PAYMENT_LINK_EXPIRY_MINUTES: Joi.number().integer().min(1).max(525600).default(4320),
  RAZORPAY_CALLBACK_URL: Joi.string().uri().allow('').optional(),
  RAZORPAY_WEBHOOK_URL: Joi.string().uri().allow('').optional(),

  SHIPPING_FREE_THRESHOLD: Joi.number().min(0).default(900),
  SHIPPING_FLAT_FEE: Joi.number().min(0).default(50),
  SHIPWAY_REQUIRED: Joi.string().valid('true', 'false').default('false'),
  SHIPWAY_EMAIL: Joi.string().when('SHIPWAY_REQUIRED', {
    is: 'true',
    then: Joi.required(),
    otherwise: Joi.allow('').optional(),
  }),
  SHIPWAY_LICENSE_KEY: Joi.string().when('SHIPWAY_REQUIRED', {
    is: 'true',
    then: Joi.required(),
    otherwise: Joi.allow('').optional(),
  }),
  SHIPWAY_BASE_URL: Joi.string().uri().default('https://app.shipway.com'),
  SHIPWAY_TRACKING_BASE_URL: Joi.string().uri().default('https://shipway.in'),
  SHIPWAY_CLASSIC_BASE_URL: Joi.string().uri().allow('').optional(),
  SHIPWAY_WAREHOUSE_ID: Joi.string().allow('').optional(),
  SHIPWAY_RETURN_WAREHOUSE_ID: Joi.string().allow('').optional(),
  SHIPWAY_CARRIER_ID: Joi.number().integer().positive().allow('').optional(),
  SHIPWAY_REVERSE_CARRIER_ID: Joi.number().integer().positive().allow('').optional(),
  SHIPWAY_REVERSE_FLAG: Joi.string().valid('true', 'false').default('false'),
  SHIPWAY_WEBHOOK_SECRET: Joi.string().allow('').optional(),
  SHIPWAY_WEBHOOK_FRESH_MS: Joi.number().integer().min(0).max(86400000).default(900000),
  SHIPWAY_TIMEOUT_MS: Joi.number().integer().min(1000).max(60000).default(15000),
  SHIPWAY_DEFAULT_WEIGHT_GRAMS: Joi.number().positive().default(500),
  SHIPWAY_DEFAULT_LENGTH_CM: Joi.number().positive().default(10),
  SHIPWAY_DEFAULT_BREADTH_CM: Joi.number().positive().default(10),
  SHIPWAY_DEFAULT_HEIGHT_CM: Joi.number().positive().default(5),
  SHIPROCKET_EMAIL: Joi.string().allow('').optional(),
  SHIPROCKET_LICENSE_KEY: Joi.string().allow('').optional(),
  SHIPROCKET_BASE_URL: Joi.string().uri().allow('').optional(),
  SHIPROCKET_TIMEOUT_MS: Joi.number().integer().min(1000).max(60000).allow('').optional(),
  SHIPROCKET_CHECKOUT_SESSION_PATH: Joi.string().allow('').optional(),
  SHIPROCKET_CHECKOUT_VERIFY_PATH: Joi.string().allow('').optional(),
  SHIPROCKET_CHECKOUT_WEBHOOK_SECRET: Joi.string().allow('').optional(),
  /** Public storefront origin used for Razorpay payment-link redirect after checkout. */
  STOREFRONT_URL: Joi.string().uri().allow('').optional(),
  SITEMAP_ENABLED: Joi.string().valid('true', 'false').default('true'),
  SITEMAP_BASE_URL: Joi.string().uri().optional(),
  SITEMAP_BATCH_SIZE: Joi.number().integer().min(100).max(50000).default(10000),
  SITEMAP_MAX_URLS_PER_FILE: Joi.number().integer().min(1).max(50000).default(50000),
  SITEMAP_DEBOUNCE_MS: Joi.number().integer().min(0).max(3600000).default(60000),
  SITEMAP_REGENERATION_INTERVAL: Joi.number().integer().min(60).max(86400).default(3600),
  SITEMAP_STORAGE_PATH: Joi.string().default('sitemaps'),
  SITEMAP_FORCE_FULL_REBUILD: Joi.string().valid('true', 'false').default('false'),

  CASHFREE_APP_ID: Joi.string().allow('').optional(),
  CASHFREE_SECRET_KEY: Joi.string().allow('').optional(),
  CASHFREE_ENV: Joi.string()
    .valid('sandbox', 'production', 'SANDBOX', 'PRODUCTION')
    .default('sandbox'),
  CASHFREE_API_VERSION: Joi.string().default('2023-08-01'),
  CASHFREE_WEBHOOK_SECRET: Joi.string().allow('').optional(),

  GOKWIK_CALLBACK_SECRET: Joi.string().allow('').optional(),
  GOKWIK_BASE_URL: Joi.string().uri().allow('').optional(),
  GOKWIK_APP_ID: Joi.string().allow('').optional(),
  GOKWIK_APP_SECRET: Joi.string().allow('').optional(),
  GOKWIK_MERCHANT_ID: Joi.string().allow('').optional(),
  GOKWIK_CALLBACK_AUTH_REQUIRED: Joi.string().valid('true', 'false').default('false'),
  GOKWIK_WEBHOOK_ENABLED: Joi.string().valid('true', 'false').default('false'),
  GOKWIK_WEBHOOK_SECRET: Joi.string().allow('').optional(),
  GOKWIK_CATALOG_SYNC_ENABLED: Joi.string().valid('true', 'false').default('false'),
  GOKWIK_ORIGIN_CITY: Joi.string().allow('').optional(),
  GOKWIK_ORIGIN_STATE: Joi.string().allow('').optional(),
  GOKWIK_ORIGIN_PINCODE: Joi.string()
    .pattern(/^\d{6}$/)
    .allow('')
    .optional(),
  GOKWIK_ORIGIN_COUNTRY: Joi.string().default('India'),
  GOKWIK_TIMEOUT_MS: Joi.number().integer().min(1000).max(60000).allow('').optional(),
  GOKWIK_CHECKOUT_TOKEN_SECRET: Joi.string().allow('').optional(),
  GOKWIK_CHECKOUT_TOKEN_TTL_SECONDS: Joi.number().integer().min(300).max(86400).optional(),
  KWIKPASS_ENVIRONMENT: Joi.string().valid('sandbox', 'production').default('sandbox'),
  KWIKPASS_MERCHANT_ID: Joi.string().allow('').optional(),
  KWIKPASS_JWE_SECRET: Joi.string().allow('').optional(),
  KWIKPASS_JWE_ISSUER: Joi.string().allow('').optional(),
  KWIKPASS_JWE_AUDIENCE: Joi.string().allow('').optional(),

  BOB_GUEST_ID: Joi.string().allow('').optional(),
  BOB_API_KEY: Joi.string().allow('').optional(),
  BOB_AUTH_REQUIRED: Joi.string().valid('true', 'false').optional(),
  BOB_NOTIFY_URL: Joi.string().uri().allow('').optional(),
  BOB_WEBHOOK_SECRET: Joi.string().allow('').optional(),
  BOB_TIMEOUT_MS: Joi.number().integer().min(1000).max(60000).default(15000),
  BOB_ABANDONED_CART_ENABLED: Joi.string().valid('true', 'false').default('true'),
  BOB_ABANDONED_CART_SCAN_INTERVAL_MINUTES: Joi.number().integer().min(5).max(1440).default(30),
  BOB_ABANDONED_CART_INACTIVITY_MINUTES: Joi.number().integer().min(5).max(1440).default(30),
  BOB_ABANDONED_CART_COOLDOWN_HOURS: Joi.number().integer().min(1).max(168).default(24),
  BOB_ABANDONED_CART_BATCH_SIZE: Joi.number().integer().min(1).max(500).default(50),
  BOB_ABANDONED_CART_MAX_BATCHES_PER_SCAN: Joi.number().integer().min(1).max(200).default(40),
  BOB_ABANDONED_CART_CONCURRENCY: Joi.number().integer().min(1).max(20).default(2),
  BOB_ABANDONED_CART_MAX_ATTEMPTS: Joi.number().integer().min(1).max(10).default(3),
  // Legacy Send-a-Template env — ignored. Do not call /wabiz/send.
  WHATSAPP_ENABLED: Joi.string().valid('true', 'false').optional(),
  WHATSAPP_SEND_URL: Joi.string().allow('').optional(),
  WHATSAPP_API_KEY: Joi.string().allow('').optional(),
  WHATSAPP_TIMEOUT_MS: Joi.number().integer().min(1000).max(60000).optional(),

  RETURN_SHIPPING_REFUNDABLE: Joi.string().valid('true', 'false').optional(),
  RETURN_COD_FEE_REFUNDABLE: Joi.string().valid('true', 'false').optional(),
  RETURN_HANDLING_REFUNDABLE: Joi.string().valid('true', 'false').optional(),
  RETURN_PICKUP_PROVIDER: Joi.string().valid('MANUAL', 'SHIPWAY', 'UNICOMMERCE').optional(),
  RETURN_AUTO_SCHEDULE_ON_APPROVE: Joi.string().valid('true', 'false').optional(),
  RETURN_NOTIFY_UNICOMMERCE: Joi.string().valid('true', 'false').optional(),
  RETURN_NOTIFY_SHIPWAY: Joi.string().valid('true', 'false').optional(),
  RETURN_REPLACEMENT_AUTO_CREATE_ENABLED: Joi.string().valid('true', 'false').optional(),
  RETURN_RESTOCK_ON_QC_PASS: Joi.string().valid('true', 'false').optional(),
  RETURN_WALLET_REFUND_ENABLED: Joi.string().valid('true', 'false').optional(),
  BANK_ACCOUNT_ENCRYPTION_KEY: Joi.string().allow('').optional(),

  /**
   * true  = managed stock ↔ OOS sync + qty enforcement + OOS email on stock or flag
   * false = legacy flag-only (stock independent; email only when outOfStock flips)
   * Default: true
   */
  STOCK_INVENTORY_MANAGEMENT_ENABLED: Joi.string().valid('true', 'false').default('true'),

  /** Temporary: allow creating bundles that reuse SKUs from existing simples. */
  ALLOW_DUPLICATE_SKU_FOR_BUNDLES: Joi.string().valid('true', 'false').default('false'),

  SUBSCRIPTION_TIMEZONE: Joi.string().default('Asia/Kolkata'),
  SUBSCRIPTION_DELIVERY_LEAD_DAYS: Joi.number().integer().min(0).max(30).default(2),
  SUBSCRIPTION_MAX_RETRIES: Joi.number().integer().min(0).max(10).default(3),
  SUBSCRIPTION_CHANGE_CUTOFF_HOURS: Joi.number().integer().min(0).max(168).default(12),
  SUBSCRIPTION_PREDEBIT_HOURS: Joi.number().integer().min(0).max(72).default(24),
  SUBSCRIPTION_AUTOPAY_ENABLED: Joi.string().valid('true', 'false').default('false'),
  SUBSCRIPTION_AUTOPAY_PROVIDER: Joi.string().valid('RAZORPAY', 'CASHFREE', '').optional(),
  SUBSCRIPTION_MANDATE_MAX_AMOUNT: Joi.number().positive().allow('').optional(),
  SUBSCRIPTION_PAYMENT_LINK_EXPIRY_HOURS: Joi.number().integer().min(1).max(720).default(72),

  TYPESENSE_HOST: Joi.string().allow('').optional(),
  TYPESENSE_API_KEY: Joi.string().allow('').optional(),
  TYPESENSE_SEARCH_API_KEY: Joi.string().allow('').optional(),
  TYPESENSE_COLLECTION: Joi.string().default('products'),

  // MSG91 SMS — env: enabled + auth key only; templates/flow/DLT → apps/api/config/msg91.constants.ts
  MSG91_ENABLED: Joi.string().valid('true', 'false').default('false'),
  MSG91_AUTH_KEY: Joi.string().allow('').optional(),

  SMTP_HOST: Joi.string().allow('').optional(),
  SMTP_PORT: Joi.number().integer().min(1).max(65535).default(587),
  SMTP_SECURE: Joi.string().valid('true', 'false').optional(),
  SMTP_USER: Joi.string().allow('').optional(),
  SMTP_PASS: Joi.string().allow('').optional(),
  SMTP_FROM: Joi.string().allow('').optional(),
});
