// import * as Joi from 'joi';

// export const envValidationSchema = Joi.object({
//   NODE_ENV: Joi.string().valid('development', 'production', 'test', 'staging').default('development'),
//   PORT: Joi.number().default(3000),
//   DATABASE_URL: Joi.string().uri().required(),
//   REDIS_HOST: Joi.string().default('localhost'),
//   REDIS_PORT: Joi.number().default(6379),
//   REDIS_PASSWORD: Joi.string().allow('').optional(),
//   CACHE_TTL: Joi.number().default(300),
//   JWT_SECRET: Joi.string().min(32).required(),
//   JWT_EXPIRES_IN: Joi.string().default('7d'),
//   JWT_ACCESS_EXPIRES_IN: Joi.string().default('15m'),
//   JWT_REFRESH_EXPIRES_IN_DAYS: Joi.number().integer().min(1).max(365).default(90),
//   LOG_LEVEL: Joi.string().valid('fatal', 'error', 'warn', 'info', 'debug', 'trace').default('info'),
//   CORS_ORIGINS: Joi.string().optional(),
//   DATABASE_LOGGING: Joi.string().valid('true', 'false').optional(),
//   STORAGE_DRIVER: Joi.string().valid('local', 'gcs').default('local'),
//   UPLOAD_DIR: Joi.string().optional(),
//   UPLOAD_MAX_FILE_SIZE: Joi.number().default(5242880),
//   UPLOAD_ALLOWED_MIME_TYPES: Joi.string().optional(),
// });

import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string()
    .valid('development', 'production', 'test', 'staging')
    .default('development'),
  PORT: Joi.number().default(3000),
  DATABASE_URL: Joi.string().uri().required(),
  REDIS_HOST: Joi.string().default('localhost'),
  REDIS_PORT: Joi.number().default(6379),
  REDIS_PASSWORD: Joi.string().allow('').optional(),
  REDIS_USERNAME: Joi.string().allow('').optional(),
  REDIS_TLS: Joi.string().valid('true', 'false').default('false'),
  CACHE_TTL: Joi.number().default(300),
  ATTRIBUTE_CACHE_TTL: Joi.number().default(300),
  BRAND_CACHE_TTL: Joi.number().default(300),
  CATEGORY_CACHE_TTL: Joi.number().default(600),
  PRODUCT_CACHE_TTL: Joi.number().default(900),
  HOMEPAGE_CACHE_TTL: Joi.number().default(600),
  SESSION_CACHE_TTL: Joi.number().default(300),
  OTP_RESEND_COOLDOWN_SECONDS: Joi.number().integer().min(30).max(300).default(60),
  OTP_MOBILE_MAX_REQUESTS: Joi.number().integer().min(1).max(50).default(5),
  OTP_IP_MAX_REQUESTS: Joi.number().integer().min(1).max(500).default(60),
  OTP_RATE_LIMIT_WINDOW_SECONDS: Joi.number().integer().min(60).max(3600).default(900),
  REDIS_CONNECT_TIMEOUT_MS: Joi.number().integer().min(500).default(5000),
  REDIS_OPERATION_TIMEOUT_MS: Joi.number().integer().min(500).default(8000),
  JWT_SECRET: Joi.string().min(32).required(),
  JWT_EXPIRES_IN: Joi.string().default('7d'),
  JWT_ACCESS_EXPIRES_IN: Joi.string().default('15m'),
  JWT_REFRESH_EXPIRES_IN_DAYS: Joi.number().integer().min(1).max(365).default(90),
  // Optional — LoggerModule resolves development→debug, production/staging→info, test→silent
  LOG_LEVEL: Joi.string()
    .valid('fatal', 'error', 'warn', 'info', 'debug', 'trace', 'silent')
    .optional(),
  CORS_ORIGINS: Joi.string().allow('').optional(),
  COOKIE_SECURE: Joi.string().valid('true', 'false').optional(),
  DATABASE_LOGGING: Joi.string().valid('true', 'false').optional(),
  STORAGE_DRIVER: Joi.string().valid('local', 'gcs').default('local'),
  UPLOAD_DIR: Joi.string().optional(),
  UPLOAD_MAX_IMAGE_FILE_SIZE: Joi.number().default(5242880),
  UPLOAD_MAX_VIDEO_FILE_SIZE: Joi.number().default(20971520),
  PRODUCT_BULK_UPLOAD_MAX_IMAGE_SIZE: Joi.number().integer().min(1048576).default(5242880),
  PRODUCT_BULK_UPLOAD_MAX_SHEET_SIZE: Joi.number().integer().min(1048576).default(41943040),
  PRODUCT_BULK_UPLOAD_LOCK_TTL_MS: Joi.number().integer().min(1200000).default(1800000),
  UPLOAD_MAX_MULTIPART_FILES: Joi.number().integer().min(1).max(200).default(50),
  UPLOAD_ALLOWED_MIME_TYPES: Joi.string().optional(),
  GCS_BUCKET_NAME: Joi.string().when('STORAGE_DRIVER', {
    is: 'gcs',
    then: Joi.required(),
    otherwise: Joi.optional(),
  }),
  GCS_CREDENTIALS_PATH: Joi.string().when('STORAGE_DRIVER', {
    is: 'gcs',
    then: Joi.required(),
    otherwise: Joi.optional(),
  }),
  GCS_SIGNED_URL_TTL_SECONDS: Joi.number().integer().min(60).max(604800).default(3600),
  // Unicommerce integration credentials — issued by Cureka to Unicommerce per seller
  UNICOMMERCE_USERNAME: Joi.string().optional(),
  UNICOMMERCE_PASSWORD: Joi.string().optional(),
  UNICOMMERCE_TENANT: Joi.string().optional(),
  UNICOMMERCE_CHANNEL: Joi.string().optional(),
  UNICOMMERCE_DEFAULT_FACILITY_CODE: Joi.string().optional(),
  UNICOMMERCE_DEFAULT_HSN_CODE: Joi.string().optional(),
  UNICOMMERCE_PRODUCT_BASE_URL: Joi.string().uri().optional(),
  // Outbound order push — Unicommerce official tenant API (OAuth 2.0)
  UNICOMMERCE_ORDER_PUSH_ENABLED: Joi.string().valid('true', 'false').optional(),
  UNICOMMERCE_ORDER_CURRENCY: Joi.string().allow('').optional(),
  UNICOMMERCE_ORDER_TIMEOUT_MS: Joi.number().integer().min(1000).optional(),
  UNICOMMERCE_PRODUCT_PUSH_ENABLED: Joi.string().valid('true', 'false').optional(),
  UNICOMMERCE_PRODUCT_PUSH_BASE_URL: Joi.string().uri().optional(),
  UNICOMMERCE_PRODUCT_PUSH_TIMEOUT_MS: Joi.number().integer().min(1000).optional(),
  UNICOMMERCE_CATEGORY_CODE: Joi.string().allow('').optional(),
  RAZORPAY_KEY_ID: Joi.string().optional(),
  RAZORPAY_SECRET: Joi.string().optional(),
  RAZORPAY_WEBHOOK_SECRET: Joi.string().optional(),
  RAZORPAY_PAYMENT_LINK_EXPIRY_MINUTES: Joi.number().integer().min(1).max(525600).default(4320),
  RAZORPAY_CALLBACK_URL: Joi.string().uri().optional(),
  RAZORPAY_WEBHOOK_URL: Joi.string().uri().optional(),

  SHIPPING_FREE_THRESHOLD: Joi.number().min(0).default(900),
  SHIPPING_FLAT_FEE: Joi.number().min(0).default(50),
  SHIPWAY_REQUIRED: Joi.string().valid('true', 'false').default('false'),
  SHIPWAY_EMAIL: Joi.string().when('SHIPWAY_REQUIRED', {
    is: 'true',
    then: Joi.required(),
    otherwise: Joi.allow('').optional(),
  }),
  SHIPWAY_LICENSE_KEY: Joi.string().when('SHIPWAY_REQUIRED', {
    is: 'true',
    then: Joi.required(),
    otherwise: Joi.allow('').optional(),
  }),
  SHIPWAY_BASE_URL: Joi.string().uri().default('https://app.shipway.com'),
  SHIPWAY_TRACKING_BASE_URL: Joi.string().uri().default('https://shipway.in'),
  SHIPWAY_CLASSIC_BASE_URL: Joi.string().uri().optional(),
  SHIPWAY_WAREHOUSE_ID: Joi.string().allow('').optional(),
  SHIPWAY_RETURN_WAREHOUSE_ID: Joi.string().allow('').optional(),
  SHIPWAY_CARRIER_ID: Joi.number().integer().positive().allow('').optional(),
  SHIPWAY_WEBHOOK_SECRET: Joi.string().allow('').optional(),
  SHIPWAY_TIMEOUT_MS: Joi.number().integer().min(1000).max(60000).default(15000),
  SHIPWAY_DEFAULT_WEIGHT_GRAMS: Joi.number().positive().default(500),
  SHIPWAY_DEFAULT_LENGTH_CM: Joi.number().positive().default(10),
  SHIPWAY_DEFAULT_BREADTH_CM: Joi.number().positive().default(10),
  SHIPWAY_DEFAULT_HEIGHT_CM: Joi.number().positive().default(5),
  SHIPROCKET_EMAIL: Joi.string().allow('').optional(),
  SHIPROCKET_LICENSE_KEY: Joi.string().allow('').optional(),
  SHIPROCKET_BASE_URL: Joi.string().uri().optional(),
  SHIPROCKET_TIMEOUT_MS: Joi.number().integer().min(1000).max(60000).optional(),
  SHIPROCKET_CHECKOUT_SESSION_PATH: Joi.string().optional(),
  SHIPROCKET_CHECKOUT_VERIFY_PATH: Joi.string().optional(),
  SHIPROCKET_CHECKOUT_WEBHOOK_SECRET: Joi.string().allow('').optional(),
  /** Public storefront origin used for Razorpay payment-link redirect after checkout. */
  STOREFRONT_URL: Joi.string().uri().optional(),
  SITEMAP_ENABLED: Joi.string().valid('true', 'false').default('true'),
  SITEMAP_BASE_URL: Joi.string().uri().optional(),
  SITEMAP_BATCH_SIZE: Joi.number().integer().min(100).max(50000).default(10000),
  SITEMAP_MAX_URLS_PER_FILE: Joi.number().integer().min(1).max(50000).default(50000),
  SITEMAP_DEBOUNCE_MS: Joi.number().integer().min(0).max(3600000).default(60000),
  SITEMAP_REGENERATION_INTERVAL: Joi.number().integer().min(60).max(86400).default(3600),
  SITEMAP_STORAGE_PATH: Joi.string().default('sitemaps'),
  SITEMAP_FORCE_FULL_REBUILD: Joi.string().valid('true', 'false').default('false'),

  CASHFREE_APP_ID: Joi.string().optional(),
  CASHFREE_SECRET_KEY: Joi.string().optional(),
  CASHFREE_ENV: Joi.string()
    .valid('sandbox', 'production', 'SANDBOX', 'PRODUCTION')
    .default('sandbox'),
  CASHFREE_API_VERSION: Joi.string().default('2023-08-01'),
  CASHFREE_WEBHOOK_SECRET: Joi.string().optional(),

  GOKWIK_CALLBACK_SECRET: Joi.string().allow('').optional(),
  GOKWIK_BASE_URL: Joi.string().uri().allow('').optional(),
  GOKWIK_APP_ID: Joi.string().allow('').optional(),
  GOKWIK_APP_SECRET: Joi.string().allow('').optional(),
  GOKWIK_MERCHANT_ID: Joi.string().allow('').optional(),
  GOKWIK_CALLBACK_AUTH_REQUIRED: Joi.string().valid('true', 'false').default('false'),
  GOKWIK_WEBHOOK_ENABLED: Joi.string().valid('true', 'false').default('false'),
  GOKWIK_WEBHOOK_SECRET: Joi.string().allow('').optional(),
  GOKWIK_CATALOG_SYNC_ENABLED: Joi.string().valid('true', 'false').default('false'),
  GOKWIK_ORIGIN_CITY: Joi.string().allow('').optional(),
  GOKWIK_ORIGIN_STATE: Joi.string().allow('').optional(),
  GOKWIK_ORIGIN_PINCODE: Joi.string()
    .pattern(/^\d{6}$/)
    .allow('')
    .optional(),
  GOKWIK_ORIGIN_COUNTRY: Joi.string().default('India'),
  GOKWIK_TIMEOUT_MS: Joi.number().integer().min(1000).max(60000).optional(),
  KWIKPASS_ENVIRONMENT: Joi.string().valid('sandbox', 'production').default('sandbox'),
  KWIKPASS_MERCHANT_ID: Joi.string().allow('').optional(),
  KWIKPASS_JWE_SECRET: Joi.string().allow('').optional(),
  KWIKPASS_JWE_ISSUER: Joi.string().allow('').optional(),
  KWIKPASS_JWE_AUDIENCE: Joi.string().allow('').optional(),

  TYPESENSE_HOST: Joi.string().optional(),
  TYPESENSE_API_KEY: Joi.string().optional(),
  TYPESENSE_SEARCH_API_KEY: Joi.string().optional(),
  TYPESENSE_COLLECTION: Joi.string().default('products'),

  // WhatsApp (Bonb) — connection only; templates → apps/api/config/whatsapp.constants.ts
  WHATSAPP_ENABLED: Joi.string().valid('true', 'false').default('false'),
  WHATSAPP_SEND_URL: Joi.string().uri().allow('').optional(),
  WHATSAPP_API_KEY: Joi.string().allow('').optional(),
  WHATSAPP_TIMEOUT_MS: Joi.number().integer().min(1000).max(60000).default(15000),

  // MSG91 SMS — env: enabled + auth key only; templates/flow/DLT → apps/api/config/msg91.constants.ts
  MSG91_ENABLED: Joi.string().valid('true', 'false').default('false'),
  MSG91_AUTH_KEY: Joi.string().allow('').optional(),
});
