export enum MembershipBenefitType {
  FREE_SHIPPING = 'FREE_SHIPPING',
  MEMBER_DISCOUNT = 'MEMBER_DISCOUNT',
  EARLY_ACCESS = 'EARLY_ACCESS',
  PRIORITY_ACCESS = 'PRIORITY_ACCESS',
  CONSULTATION_OFFER = 'CONSULTATION_OFFER',
}
