export enum ProductSubscriptionStatus {
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  ACTIVE = 'ACTIVE',
  RENEWAL_PAYMENT_PENDING = 'RENEWAL_PAYMENT_PENDING',
  PAUSED = 'PAUSED',
  PAST_DUE = 'PAST_DUE',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}
