export enum SubscriptionPaymentStatus {
  PENDING = 'PENDING',
  LINK_GENERATED = 'LINK_GENERATED',
  RECONCILING = 'RECONCILING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}
