export enum SubscriptionBillingCycleStatus {
  SCHEDULED = 'SCHEDULED',
  SKIPPED = 'SKIPPED',
  NOTIFICATION_SENT = 'NOTIFICATION_SENT',
  DEBIT_PENDING = 'DEBIT_PENDING',
  LINK_GENERATED = 'LINK_GENERATED',
  PAID = 'PAID',
  PAID_ORDER_PENDING = 'PAID_ORDER_PENDING',
  FAILED = 'FAILED',
  EXHAUSTED = 'EXHAUSTED',
}
