export enum PaymentRequestStatus {
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  LINK_GENERATED = 'LINK_GENERATED',
  PAID = 'PAID',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}
