export enum CodPayoutStatus {
  PENDING_DETAILS = 'PENDING_DETAILS',
  DETAILS_SUBMITTED = 'DETAILS_SUBMITTED',
  UNDER_VERIFICATION = 'UNDER_VERIFICATION',
  READY_FOR_PAYOUT = 'READY_FOR_PAYOUT',
  PROCESSING = 'PROCESSING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  ON_HOLD = 'ON_HOLD',
  CANCELLED = 'CANCELLED',
}
