export const BANK_DETAILS_REQUIRED = 'BANK_DETAILS_REQUIRED';
export const BANK_ACCOUNT_MISMATCH = 'BANK_ACCOUNT_MISMATCH';
export const INVALID_IFSC = 'INVALID_IFSC';
export const BANK_DETAILS_LOCKED = 'BANK_DETAILS_LOCKED';
export const BANK_DETAILS_NOT_APPLICABLE = 'BANK_DETAILS_NOT_APPLICABLE';
export const BANK_DETAILS_ACCESS_DENIED = 'BANK_DETAILS_ACCESS_DENIED';
export const WALLET_REFUND_NOT_ENABLED = 'WALLET_REFUND_NOT_ENABLED';
export const COD_PAYOUT_NOT_FOUND = 'COD_PAYOUT_NOT_FOUND';
export const COD_PAYOUT_UTR_REQUIRED = 'COD_PAYOUT_UTR_REQUIRED';
export const COD_PAYOUT_ALREADY_PAID = 'COD_PAYOUT_ALREADY_PAID';
export const COD_PAYOUT_INVALID_STATUS = 'COD_PAYOUT_INVALID_STATUS';
export const COD_PAYOUT_DUPLICATE = 'COD_PAYOUT_DUPLICATE';
export const COD_REFUND_METHOD_REQUIRED = 'COD_REFUND_METHOD_REQUIRED';
export const BANK_ENCRYPTION_NOT_CONFIGURED = 'BANK_ENCRYPTION_NOT_CONFIGURED';
export const COD_PAYOUT_RATE_LIMITED = 'COD_PAYOUT_RATE_LIMITED';

export const COD_REFUND_INITIATED_CUSTOMER_MESSAGE =
  'Your refund request has been initiated. It may take 5–7 working days after approval.';

export const COD_PAYOUT_PERMISSIONS = {
  READ: 'refund_payouts.read',
  UPDATE: 'refund_payouts.update',
  STATUS: 'refund_payouts.status',
} as const;
