export const REFUND_REQUEST_NOT_FOUND = 'REFUND_REQUEST_NOT_FOUND';
export const REFUND_REQUEST_ALREADY_EXISTS = 'REFUND_REQUEST_ALREADY_EXISTS';
export const REFUND_NOT_REQUIRED = 'REFUND_NOT_REQUIRED';
export const REFUND_AMOUNT_INVALID = 'REFUND_AMOUNT_INVALID';
export const REFUND_AMOUNT_EXCEEDS_AVAILABLE_AMOUNT = 'REFUND_AMOUNT_EXCEEDS_AVAILABLE_AMOUNT';
export const REFUND_INVALID_STATUS_TRANSITION = 'REFUND_INVALID_STATUS_TRANSITION';
export const REFUND_NOT_APPROVED = 'REFUND_NOT_APPROVED';
export const REFUND_ALREADY_INITIATED = 'REFUND_ALREADY_INITIATED';
export const REFUND_ALREADY_PROCESSED = 'REFUND_ALREADY_PROCESSED';
export const REFUND_PROVIDER_NOT_FOUND = 'REFUND_PROVIDER_NOT_FOUND';
export const REFUND_PROVIDER_NOT_SUPPORTED = 'REFUND_PROVIDER_NOT_SUPPORTED';
export const REFUND_PROVIDER_REQUEST_FAILED = 'REFUND_PROVIDER_REQUEST_FAILED';
export const REFUND_RETRY_NOT_ALLOWED = 'REFUND_RETRY_NOT_ALLOWED';
export const REFUND_PERMISSION_DENIED = 'REFUND_PERMISSION_DENIED';
export const REFUND_FULL_AMOUNT_REQUIRED = 'REFUND_FULL_AMOUNT_REQUIRED';

export const REFUND_CREDIT_WINDOW_MESSAGE =
  'Once approved and processed, the amount will be credited to your original payment method within 5–7 working days.';

export const REFUND_REQUEST_INITIATED_CUSTOMER_MESSAGE = `Your refund request has been initiated. ${REFUND_CREDIT_WINDOW_MESSAGE}`;

export const REFUND_CURRENCY = 'INR';

/** Pending client confirmation — used only for computed SLA badges. */
export const REFUND_SLA_ORANGE_AFTER_HOURS = 24;
export const REFUND_SLA_RED_AFTER_HOURS = 72;
