export const COD_BLOCKLIST_NOT_FOUND = 'COD_BLOCKLIST_NOT_FOUND';
export const COD_BLOCKLIST_INVALID_PINCODE = 'COD_BLOCKLIST_INVALID_PINCODE';
export const COD_BLOCKLIST_INVALID_CUSTOMER = 'COD_BLOCKLIST_INVALID_CUSTOMER';
export const COD_BLOCKLIST_INVALID_MOBILE = 'COD_BLOCKLIST_INVALID_MOBILE';
export const COD_BLOCKLIST_TYPE_IMMUTABLE = 'COD_BLOCKLIST_TYPE_IMMUTABLE';
export const COD_BLOCKLIST_SEARCH_TOO_SHORT = 'COD_BLOCKLIST_SEARCH_TOO_SHORT';

export const COD_BLOCKLIST_CUSTOMER_SEARCH_MIN_LENGTH = 2;
