import { PermissionAction } from '../enums/permission-action.enum';

export interface IPermissionSeed {
  name: string;
  code: string;
  module: string;
  action: PermissionAction;
  description?: string;
}

const buildCrudPermissions = (module: string, label: string): IPermissionSeed[] => [
  {
    name: `View ${label}`,
    code: `${module}.read`,
    module,
    action: PermissionAction.READ,
  },
  {
    name: `Create ${label}`,
    code: `${module}.create`,
    module,
    action: PermissionAction.CREATE,
  },
  {
    name: `Update ${label}`,
    code: `${module}.update`,
    module,
    action: PermissionAction.UPDATE,
  },
  {
    name: `Change ${label} Status`,
    code: `${module}.status`,
    module,
    action: PermissionAction.STATUS,
  },
  {
    name: `Delete ${label}`,
    code: `${module}.delete`,
    module,
    action: PermissionAction.DELETE,
  },
];

/** View + download for a single report screen (export uses action `read` — enum has no export). */
const buildReportPermissions = (module: string, label: string): IPermissionSeed[] => [
  {
    name: `View ${label} Report`,
    code: `${module}.read`,
    module,
    action: PermissionAction.READ,
  },
  {
    name: `Download ${label} Report`,
    code: `${module}.export`,
    module,
    action: PermissionAction.READ,
  },
];

export const ADMIN_PERMISSION_SEEDS: readonly IPermissionSeed[] = [
  {
    name: 'View Dashboard',
    code: 'dashboard.read',
    module: 'dashboard',
    action: PermissionAction.READ,
  },
  ...buildReportPermissions('reports_sales_revenue', 'Sales & Revenue'),
  ...buildReportPermissions('reports_orders', 'Orders'),
  ...buildReportPermissions('reports_product_performance', 'Product Performance'),
  ...buildReportPermissions('reports_inventory_stock', 'Inventory & Stock'),
  ...buildReportPermissions('reports_customers', 'Customers'),
  ...buildReportPermissions('reports_payments', 'Payments'),
  ...buildReportPermissions('reports_returns_refunds', 'Returns & Refunds'),
  ...buildReportPermissions('reports_coupons', 'Coupons & Promotions'),
  ...buildReportPermissions('reports_vendor_performance', 'Vendor Performance'),
  ...buildReportPermissions('reports_consultations', 'Consultations'),
  ...buildCrudPermissions('users', 'Users'),
  ...buildCrudPermissions('vendors', 'Vendors'),
  ...buildCrudPermissions('orders', 'Orders'),
  {
    name: 'View Payment Requests',
    code: 'payment-request.read',
    module: 'payment-request',
    action: PermissionAction.READ,
  },
  {
    name: 'Create Payment Requests',
    code: 'payment-request.create',
    module: 'payment-request',
    action: PermissionAction.CREATE,
  },
  {
    name: 'Update Payment Requests',
    code: 'payment-request.update',
    module: 'payment-request',
    action: PermissionAction.UPDATE,
  },
  {
    name: 'Delete Payment Requests',
    code: 'payment-request.delete',
    module: 'payment-request',
    action: PermissionAction.DELETE,
  },
  {
    name: 'Generate Payment Request Links',
    code: 'payment-request.generate-link',
    module: 'payment-request',
    action: PermissionAction.CREATE,
  },
  {
    name: 'Cancel Payment Requests',
    code: 'payment-request.cancel',
    module: 'payment-request',
    action: PermissionAction.UPDATE,
  },
  {
    name: 'Regenerate Payment Request Links',
    code: 'payment-request.regenerate',
    module: 'payment-request',
    action: PermissionAction.UPDATE,
  },
  {
    name: 'View Abandoned Carts',
    code: 'abandoned_carts.read',
    module: 'abandoned_carts',
    action: PermissionAction.READ,
  },
  {
    name: 'View Refund Requests',
    code: 'refund_requests.read',
    module: 'refund_requests',
    action: PermissionAction.READ,
  },
  {
    name: 'Create Refund Requests',
    code: 'refund_requests.create',
    module: 'refund_requests',
    action: PermissionAction.CREATE,
  },
  {
    name: 'Update Refund Requests',
    code: 'refund_requests.update',
    module: 'refund_requests',
    action: PermissionAction.UPDATE,
  },
  {
    name: 'Approve Refund Requests',
    code: 'refund_requests.approve',
    module: 'refund_requests',
    action: PermissionAction.APPROVE,
  },
  {
    name: 'Reject Refund Requests',
    code: 'refund_requests.reject',
    module: 'refund_requests',
    action: PermissionAction.REJECT,
  },
  {
    name: 'Initiate Refund Payments',
    code: 'refund_requests.status',
    module: 'refund_requests',
    action: PermissionAction.STATUS,
  },
  {
    name: 'View COD Refund Payouts',
    code: 'refund_payouts.read',
    module: 'refund_payouts',
    action: PermissionAction.READ,
  },
  {
    name: 'Update COD Refund Payouts',
    code: 'refund_payouts.update',
    module: 'refund_payouts',
    action: PermissionAction.UPDATE,
  },
  {
    name: 'Process COD Refund Payouts',
    code: 'refund_payouts.status',
    module: 'refund_payouts',
    action: PermissionAction.STATUS,
  },
  {
    name: 'View Returns',
    code: 'returns.read',
    module: 'returns',
    action: PermissionAction.READ,
  },
  {
    name: 'Create Returns',
    code: 'returns.create',
    module: 'returns',
    action: PermissionAction.CREATE,
  },
  {
    name: 'Update Returns',
    code: 'returns.update',
    module: 'returns',
    action: PermissionAction.UPDATE,
  },
  {
    name: 'Approve Returns',
    code: 'returns.approve',
    module: 'returns',
    action: PermissionAction.APPROVE,
  },
  {
    name: 'Reject Returns',
    code: 'returns.reject',
    module: 'returns',
    action: PermissionAction.REJECT,
  },
  {
    name: 'Progress Return Operations',
    code: 'returns.status',
    module: 'returns',
    action: PermissionAction.STATUS,
  },
  {
    name: 'View Return Policies',
    code: 'return_policies.read',
    module: 'return_policies',
    action: PermissionAction.READ,
  },
  {
    name: 'Update Return Policies',
    code: 'return_policies.update',
    module: 'return_policies',
    action: PermissionAction.UPDATE,
  },
  {
    name: 'View COD Blocklist',
    code: 'cod_blocklist.read',
    module: 'cod_blocklist',
    action: PermissionAction.READ,
  },
  {
    name: 'Create COD Blocklist',
    code: 'cod_blocklist.create',
    module: 'cod_blocklist',
    action: PermissionAction.CREATE,
  },
  {
    name: 'Update COD Blocklist',
    code: 'cod_blocklist.update',
    module: 'cod_blocklist',
    action: PermissionAction.UPDATE,
  },
  {
    name: 'Change COD Blocklist Status',
    code: 'cod_blocklist.status',
    module: 'cod_blocklist',
    action: PermissionAction.STATUS,
  },
  {
    name: 'Delete COD Blocklist',
    code: 'cod_blocklist.delete',
    module: 'cod_blocklist',
    action: PermissionAction.DELETE,
  },
  {
    name: 'View Settings',
    code: 'settings.read',
    module: 'settings',
    action: PermissionAction.READ,
  },
  {
    name: 'Update Settings',
    code: 'settings.update',
    module: 'settings',
    action: PermissionAction.UPDATE,
  },
  {
    name: 'Change Settings Status',
    code: 'settings.status',
    module: 'settings',
    action: PermissionAction.STATUS,
  },
  ...buildCrudPermissions('roles', 'Roles'),
  ...buildCrudPermissions('permissions', 'Permissions'),
  ...buildCrudPermissions('admin_users', 'Admin Users'),
  ...buildCrudPermissions('category_filters', 'Category Filters'),
  ...buildCrudPermissions('categories', 'Categories'),
  ...buildCrudPermissions('attributes', 'Attributes'),
  ...buildCrudPermissions('units', 'Units'),
  ...buildCrudPermissions('brands', 'Brands'),
  ...buildCrudPermissions('countries', 'Countries'),
  ...buildCrudPermissions('states', 'States'),
  ...buildCrudPermissions('cities', 'Cities'),
  ...buildCrudPermissions('age_groups', 'Age Groups'),
  ...buildCrudPermissions('product_natures', 'Product Natures'),
  ...buildCrudPermissions('health_concerns', 'Health Concerns'),
  ...buildCrudPermissions('wellness_goals', 'Wellness Goals'),
  ...buildCrudPermissions('reason_masters', 'Reason Masters'),
  ...buildCrudPermissions('manufacturers', 'Manufacturers'),
  ...buildCrudPermissions('packers', 'Packers'),
  ...buildCrudPermissions('importers', 'Importers'),
  ...buildCrudPermissions('subscription_frequencies', 'Subscription Frequencies'),
  ...buildCrudPermissions('coupon_codes', 'Coupon Codes'),
  ...buildCrudPermissions('membership_plans', 'Membership Plans'),
  ...buildCrudPermissions('membership_benefits', 'Membership Benefits'),
  ...buildCrudPermissions('user_memberships', 'User Memberships'),
  ...buildCrudPermissions('membership_payments', 'Membership Payments'),
  ...buildCrudPermissions('user_product_subscriptions', 'User Product Subscriptions'),
  ...buildCrudPermissions('subscription_payments', 'Subscription Payments'),
  ...buildCrudPermissions('products', 'Products'),
  {
    name: 'Approve Products',
    code: 'products.approve',
    module: 'products',
    action: PermissionAction.APPROVE,
  },
  {
    name: 'Reject Products',
    code: 'products.reject',
    module: 'products',
    action: PermissionAction.REJECT,
  },
  ...buildCrudPermissions('bundle_products', 'Bundle Products'),
  {
    name: 'Approve Bundle Products',
    code: 'bundle_products.approve',
    module: 'bundle_products',
    action: PermissionAction.APPROVE,
  },
  {
    name: 'Reject Bundle Products',
    code: 'bundle_products.reject',
    module: 'bundle_products',
    action: PermissionAction.REJECT,
  },
  ...buildCrudPermissions('product_tags', 'Product Tags'),
  ...buildCrudPermissions('product_informations', 'Product Informations'),
  ...buildCrudPermissions('gallery', 'Media Gallery'),
  ...buildCrudPermissions('banners', 'Banners'),
  ...buildCrudPermissions('home_sections', 'Home Sections'),
  ...buildCrudPermissions('header_indexing', 'Header Indexing'),
  ...buildCrudPermissions('shop_by_indexing', 'Shop By Indexing'),
  ...buildCrudPermissions('best_sellers', 'Best Sellers Indexing'),
  ...buildCrudPermissions('category_product', 'Category Product Indexing'),
  ...buildCrudPermissions('watch_and_shop', 'Watch & Shop'),
  ...buildCrudPermissions('expert_talks', 'Expert Talks'),
  ...buildCrudPermissions('testimonials', 'Testimonials'),
  ...buildCrudPermissions('cms_pages', 'CMS Pages'),
  ...buildCrudPermissions('audit_logs', 'Audit Logs'),
  ...buildCrudPermissions('support_categories', 'Support Categories'),
  ...buildCrudPermissions('support_articles', 'Support Articles'),
  ...buildCrudPermissions('support_faqs', 'Support FAQs'),
  ...buildCrudPermissions('blog_categories', 'Blog Categories'),
  ...buildCrudPermissions('blog_posts', 'Blog Posts'),
  ...buildCrudPermissions('blog_comments', 'Blog Comments'),
  {
    name: 'View Product Reviews',
    code: 'product_reviews.read',
    module: 'product_reviews',
    action: PermissionAction.READ,
  },
  {
    name: 'Update Product Reviews',
    code: 'product_reviews.update',
    module: 'product_reviews',
    action: PermissionAction.UPDATE,
  },
  {
    name: 'Change Product Review Status',
    code: 'product_reviews.status',
    module: 'product_reviews',
    action: PermissionAction.STATUS,
  },
  {
    name: 'Delete Product Reviews',
    code: 'product_reviews.delete',
    module: 'product_reviews',
    action: PermissionAction.DELETE,
  },
  {
    name: 'View Support Tickets',
    code: 'support_tickets.read',
    module: 'support',
    action: PermissionAction.READ,
  },
  {
    name: 'Update Support Tickets',
    code: 'support_tickets.update',
    module: 'support',
    action: PermissionAction.UPDATE,
  },
  {
    name: 'Assign Support Tickets',
    code: 'support_tickets.assign',
    module: 'support',
    action: PermissionAction.UPDATE,
  },
  {
    name: 'View Support Reports',
    code: 'support_reports.read',
    module: 'support',
    action: PermissionAction.READ,
  },
];
