export enum OrderFulfillmentEventType {
  CANCELLATION_REQUESTED = 'CANCELLATION_REQUESTED',
  CANCELLATION_PROCESSING = 'CANCELLATION_PROCESSING',
  CANCELLATION_CONFIRMED = 'CANCELLATION_CONFIRMED',
  CANCELLATION_REJECTED = 'CANCELLATION_REJECTED',
  CANCELLATION_REQUIRES_ATTENTION = 'CANCELLATION_REQUIRES_ATTENTION',
  UNICOMMERCE_CANCEL_SKIPPED = 'UNICOMMERCE_CANCEL_SKIPPED',
  UNICOMMERCE_CANCEL_SENT = 'UNICOMMERCE_CANCEL_SENT',
  UNICOMMERCE_CANCEL_CONFIRMED = 'UNICOMMERCE_CANCEL_CONFIRMED',
  UNICOMMERCE_CANCEL_FAILED = 'UNICOMMERCE_CANCEL_FAILED',
  UNICOMMERCE_CANCEL_UNCERTAIN = 'UNICOMMERCE_CANCEL_UNCERTAIN',
  SHIPWAY_CANCEL_SKIPPED = 'SHIPWAY_CANCEL_SKIPPED',
  SHIPWAY_CANCEL_SENT = 'SHIPWAY_CANCEL_SENT',
  SHIPWAY_CANCEL_CONFIRMED = 'SHIPWAY_CANCEL_CONFIRMED',
  SHIPWAY_CANCEL_FAILED = 'SHIPWAY_CANCEL_FAILED',
  SHIPWAY_CANCEL_UNCERTAIN = 'SHIPWAY_CANCEL_UNCERTAIN',
  EXPORT_BLOCKED = 'EXPORT_BLOCKED',
  ADMIN_RETRY = 'ADMIN_RETRY',
  ADMIN_NOTE = 'ADMIN_NOTE',
}

export enum OrderFulfillmentRequestType {
  CANCELLATION = 'CANCELLATION',
  RETURN = 'RETURN',
  NOTE = 'NOTE',
}
