export enum OrderPaymentMethod {
  COD = 'COD',
  WALLET = 'WALLET',
  RAZORPAY = 'RAZORPAY',
  CASHFREE = 'CASHFREE',
  GOKWIK_PREPAID = 'GOKWIK_PREPAID',
  GOKWIK_PARTIAL_COD = 'GOKWIK_PARTIAL_COD',
}
