import * as exceljs from 'exceljs';
import { join } from 'path';

async function run() {
  const workbook = new exceljs.Workbook();
  const worksheet = workbook.addWorksheet('Bulk Import Template');

  worksheet.columns = [
    { header: 'Product Name*', key: 'productName' },
    { header: 'Product Nature *', key: 'productNature' },
    { header: 'Product Type *', key: 'productType' },
    { header: 'Category *', key: 'category' },
    { header: 'Sub Category', key: 'subCategory' },
    { header: 'Sub Sub Category', key: 'subSubCategory' },
    { header: 'Sub Sub Sub Category', key: 'subSubSubCategory' },
    { header: 'Brand', key: 'brand' },
    { header: 'Health Concerns', key: 'healthConcerns' },
    { header: 'Wellness Goals', key: 'wellnessGoals' },
    { header: 'Product Tags', key: 'productTags' },
    { header: 'Vendor', key: 'vendor' },
    { header: 'Vendor SKU', key: 'vendorSku' },
    
    { header: 'Attribute 1 Name', key: 'attr1Name' },
    { header: 'Attribute 1 Value', key: 'attr1Val' },
    { header: 'Attribute 2 Name', key: 'attr2Name' },
    { header: 'Attribute 2 Value', key: 'attr2Val' },
    { header: 'Attribute 3 Name', key: 'attr3Name' },
    { header: 'Attribute 3 Value', key: 'attr3Val' },
    
    { header: 'Bundle SKU', key: 'bundleSku' },
    { header: 'Bundle MRP (Rs)', key: 'bundleMrp' },
    { header: 'Bundle Selling Price (Rs)', key: 'bundleSellingPrice' },
    { header: 'Child Product Name', key: 'childName' },
    { header: 'Child SKU', key: 'childSku' },
    { header: 'Child MRP (Rs)', key: 'childMrp' },
    { header: 'Child Selling Price (Rs)', key: 'childSellingPrice' },
    { header: 'Child Quantity', key: 'childQty' },
    
    { header: 'SKU Code*', key: 'skuCode' },
    { header: 'Barcode (EAN/UPC)', key: 'barcode' },
    { header: 'MRP (Rs)*', key: 'mrp' },
    { header: 'Selling Price (Rs)*', key: 'sellingPrice' },
    { header: 'Discount Percentage', key: 'discount' },
    { header: 'Tax Class', key: 'taxClass' },
    { header: 'Quantity / Stock', key: 'stock' },
    { header: 'Weight (kg)', key: 'weight' },
    { header: 'Weight Unit', key: 'weightUnit' },
    { header: 'Length (cm)', key: 'length' },
    { header: 'Width (cm)', key: 'width' },
    { header: 'Height (cm)', key: 'height' },
    { header: 'Dimension Unit', key: 'dimensionUnit' },
    { header: 'Variant Status', key: 'variantStatus' },
    
    { header: 'Product Highlights', key: 'highlights' },
    { header: 'Description', key: 'description' },
    { header: 'Key Features', key: 'keyFeatures' },
    { header: 'Usage and Safety', key: 'usageSafety' },
    { header: 'Ingredients and Nutrition', key: 'ingredients' },
    { header: 'Compliance Detail', key: 'compliance' },
    { header: 'Additional Info', key: 'additionalInfo' },
    { header: 'Key Benefits', key: 'keyBenefits' },
    { header: 'Expert Advice', key: 'expertAdvice' },
    { header: 'Key Ingredients', key: 'keyIngredients' },
    { header: 'Other Ingredients', key: 'otherIngredients' },
    { header: 'Preventive Notes', key: 'preventiveNotes' },
    { header: 'Accessories', key: 'accessories' },
    { header: 'Direction of Use', key: 'directionOfUse' },
    { header: 'Feeding Table', key: 'feedingTable' },
    { header: 'Safety Information', key: 'safetyInformation' },
    { header: 'Indications', key: 'indications' },
    { header: 'Kit Contains', key: 'kitContains' },
    { header: 'Offers', key: 'offers' },
    { header: 'FAQ 1 Question', key: 'faq1q' },
    { header: 'FAQ 1 Answer', key: 'faq1a' },
    { header: 'FAQ 2 Question', key: 'faq2q' },
    { header: 'FAQ 2 Answer', key: 'faq2a' },
    { header: 'FAQ 3 Question', key: 'faq3q' },
    { header: 'FAQ 3 Answer', key: 'faq3a' },
    
    { header: 'Primary Image Filename', key: 'primaryImage' },
    { header: 'Gallery Image 2', key: 'gallery2' },
    { header: 'Gallery Image 3', key: 'gallery3' },
    { header: 'Gallery Image 4', key: 'gallery4' },
    { header: 'Gallery Image 5', key: 'gallery5' },
    
    { header: 'Meta Title', key: 'metaTitle' },
    { header: 'Meta Description', key: 'metaDescription' },
    { header: 'Slug URL', key: 'slug' },
    { header: 'Meta Keywords', key: 'metaKeywords' },
    { header: 'Subscription Available', key: 'subscription' },
    { header: 'Return Policy', key: 'returnPolicy' },
    { header: 'Return Window Days', key: 'returnDays' },
    { header: 'COD Available', key: 'cod' },
    { header: 'EMI Available', key: 'emi' },
    { header: 'Replacement Allowed', key: 'replacement' },
    { header: 'Replacement Window Days', key: 'replacementDays' },
    
    { header: 'Manufacturer', key: 'manufacturer' },
    { header: 'Packer', key: 'packer' },
    { header: 'Importer', key: 'importer' },
    { header: 'Country of Origin', key: 'countryOfOrigin' },
    { header: 'Components', key: 'components' },
    { header: 'Shelf Life in Months', key: 'shelfLife' },
    { header: 'Product Status', key: 'status' }
  ];

  worksheet.addRow({
    productName: 'Success Simple Product Tablets',
    productNature: 'Gel',
    productType: 'simple',
    category: 'care care',
    subCategory: 'omega-100',
    brand: 'Meru Bio Herb',
    healthConcerns: 'Blood Pressure | Diabities',
    wellnessGoals: 'Digestion & Gut Health',
    productTags: 'organic | daily-pill',
    vendor: 'MeruBio',
    skuCode: 'CAR-MER-SPEC-' + Date.now().toString().slice(-4),
    mrp: '180.00',
    sellingPrice: '150.00',
    stock: '150',
    weight: '0.12',
    weightUnit: 'kg',
    length: '12',
    width: '6',
    height: '3',
    dimensionUnit: 'cm',
    variantStatus: 'active',
    highlights: 'Highly effective | Long shelf life',
    description: 'Special formulation for standard daily use.',
    keyBenefits: 'Promotes holistic health',
    expertAdvice: 'Consult physician before use.',
    faq1q: 'Is it vegan?',
    faq1a: 'Yes, it is 100% vegan.',
    primaryImage: 'dolo-front.jpg',
    subscription: 'no',
    returnPolicy: '7 Days Returnable',
    returnDays: '7',
    cod: 'yes',
    emi: 'no',
    replacement: 'yes',
    replacementDays: '7',
    status: 'draft'
  });

  worksheet.addRow({
    productName: 'Success Special Care Variant',
    productNature: 'Powder',
    productType: 'variable',
    category: 'Diabities',
    subCategory: 'Pain Relief Strong',
    brand: 'Vivo',
    healthConcerns: 'Chest pain | Care',
    wellnessGoals: 'Digestion & Gut Health',
    productTags: 'premium | muscle-care',
    vendor: 'MuscleFit',
    vendorSku: 'SPEC-VAR-PARENT-' + Date.now().toString().slice(-4),
    skuCode: 'SPEC-VAR-CHOCOLATE-' + Date.now().toString().slice(-4),
    attr1Name: 'Size',
    attr1Val: '1kg',
    mrp: '3000',
    sellingPrice: '2500',
    stock: '80',
    weight: '1',
    weightUnit: 'kg',
    length: '20',
    width: '10',
    height: '10',
    dimensionUnit: 'cm',
    variantStatus: 'active',
    highlights: 'Superior mix | High quality source',
    description: 'High-purity wellness powder.',
    keyBenefits: 'Improves muscle recovery',
    expertAdvice: 'Best consumed after workout.',
    faq1q: 'Does it have sugar?',
    faq1a: 'No added sugar.',
    primaryImage: 'whey-chocolate.jpg',
    subscription: 'yes',
    returnPolicy: 'Non-Returnable',
    cod: 'yes',
    emi: 'yes',
    replacement: 'no',
    status: 'draft'
  });

  const destPath = join(process.cwd(), 'docs', 'bulk-upload-success-sheet.xlsx');
  await workbook.xlsx.writeFile(destPath);
  console.log('Success Excel sheet created at:', destPath);
}

run().catch(console.error);
