export const CART_ITEM_NOT_FOUND = 'CART_ITEM_NOT_FOUND';
export const SAVE_FOR_LATER_ITEM_NOT_FOUND = 'SAVE_FOR_LATER_ITEM_NOT_FOUND';
export const SAVE_FOR_LATER_INVALID_QUANTITY = 'SAVE_FOR_LATER_INVALID_QUANTITY';
export const SAVE_FOR_LATER_PRODUCT_INACTIVE = 'SAVE_FOR_LATER_PRODUCT_INACTIVE';
export const SAVE_FOR_LATER_VARIANT_INACTIVE = 'SAVE_FOR_LATER_VARIANT_INACTIVE';
export const SAVE_FOR_LATER_OUT_OF_STOCK = 'SAVE_FOR_LATER_OUT_OF_STOCK';
export const SAVE_FOR_LATER_INSUFFICIENT_STOCK = 'SAVE_FOR_LATER_INSUFFICIENT_STOCK';

export type SavedForLaterUnavailableReason =
  | 'PRODUCT_INACTIVE'
  | 'PRODUCT_DELETED'
  | 'VARIANT_INACTIVE'
  | 'OUT_OF_STOCK'
  | 'INSUFFICIENT_STOCK'
  | 'MAXIMUM_QUANTITY_EXCEEDED';
