export const SUBSCRIPTION_DEFAULT_TIMEZONE = 'Asia/Kolkata';

/** BI_MONTHLY means every two calendar months — never twice per month. */
export const PRODUCT_FREQUENCY_MONTHS = {
  MONTHLY: 1,
  BI_MONTHLY: 2,
  QUARTERLY: 3,
} as const;

export const PRODUCT_FREQUENCY_LABELS = {
  MONTHLY: 'Every month',
  BI_MONTHLY: 'Every 2 months',
  QUARTERLY: 'Every 3 months',
} as const;

export const SUBSCRIPTION_ERROR = {
  MIXED_CART_UNSUPPORTED: 'SUBSCRIPTION_MIXED_CART_UNSUPPORTED',
  AUTOPAY_UNAVAILABLE: 'SUBSCRIPTION_AUTOPAY_UNAVAILABLE',
  MANDATE_LIMIT_EXCEEDED: 'SUBSCRIPTION_MANDATE_LIMIT_EXCEEDED',
  MANDATE_NOT_CONFIRMED: 'SUBSCRIPTION_MANDATE_NOT_CONFIRMED',
  CYCLE_LOCKED: 'SUBSCRIPTION_CYCLE_LOCKED',
  CYCLE_ALREADY_PAID: 'SUBSCRIPTION_CYCLE_ALREADY_PAID',
  CYCLE_IN_FLIGHT: 'SUBSCRIPTION_CYCLE_IN_FLIGHT',
  CHANGE_CUTOFF: 'SUBSCRIPTION_CHANGE_CUTOFF',
  QUANTITY_CHANGE_DISABLED: 'SUBSCRIPTION_QUANTITY_CHANGE_DISABLED',
  LEGACY_MANDATE_REQUIRED: 'SUBSCRIPTION_LEGACY_MANDATE_REQUIRED',
  PROVIDER_MISMATCH: 'SUBSCRIPTION_PROVIDER_MISMATCH',
} as const;
