/** Stable machine-readable error codes surfaced to the storefront and admin panel. */
export const RETURN_NOT_ALLOWED = 'RETURN_NOT_ALLOWED';
export const RETURN_WINDOW_EXPIRED = 'RETURN_WINDOW_EXPIRED';
export const ITEM_NOT_DELIVERED = 'ITEM_NOT_DELIVERED';
export const RETURN_QUANTITY_EXCEEDED = 'RETURN_QUANTITY_EXCEEDED';
export const ACTIVE_RETURN_ALREADY_EXISTS = 'ACTIVE_RETURN_ALREADY_EXISTS';
export const INVALID_RETURN_REASON = 'INVALID_RETURN_REASON';
export const EVIDENCE_REQUIRED = 'EVIDENCE_REQUIRED';
export const PICKUP_ADDRESS_REQUIRED = 'PICKUP_ADDRESS_REQUIRED';
export const INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION';
export const RETURN_ALREADY_REFUNDED = 'RETURN_ALREADY_REFUNDED';
export const RETURN_ALREADY_REPLACED = 'RETURN_ALREADY_REPLACED';
export const RETURN_REFUND_ALREADY_CREATED = 'RETURN_REFUND_ALREADY_CREATED';
export const RETURN_POLICY_NOT_AVAILABLE = 'RETURN_POLICY_NOT_AVAILABLE';
export const RETURN_ACCESS_DENIED = 'RETURN_ACCESS_DENIED';

export const RETURN_REQUEST_NOT_FOUND = 'RETURN_REQUEST_NOT_FOUND';
export const RETURN_ORDER_NOT_FOUND = 'RETURN_ORDER_NOT_FOUND';
export const RETURN_ITEM_NOT_FOUND = 'RETURN_ITEM_NOT_FOUND';
export const RETURN_RESOLUTION_NOT_ALLOWED = 'RETURN_RESOLUTION_NOT_ALLOWED';
export const RETURN_CONDITIONS_NOT_CONFIRMED = 'RETURN_CONDITIONS_NOT_CONFIRMED';
export const RETURN_COMMENTS_REQUIRED = 'RETURN_COMMENTS_REQUIRED';
export const RETURN_CANCELLATION_NOT_ALLOWED = 'RETURN_CANCELLATION_NOT_ALLOWED';
export const RETURN_ORDER_IS_RTO = 'RETURN_ORDER_IS_RTO';
export const RETURN_PICKUP_NOT_REQUIRED = 'RETURN_PICKUP_NOT_REQUIRED';
export const RETURN_PICKUP_NOT_FOUND = 'RETURN_PICKUP_NOT_FOUND';
export const RETURN_PICKUP_PROVIDER_UNAVAILABLE = 'RETURN_PICKUP_PROVIDER_UNAVAILABLE';
export const RETURN_QC_NOT_ALLOWED = 'RETURN_QC_NOT_ALLOWED';
export const RETURN_QC_QUANTITY_INVALID = 'RETURN_QC_QUANTITY_INVALID';
export const RETURN_NO_PICKUP_NOT_ALLOWED = 'RETURN_NO_PICKUP_NOT_ALLOWED';
export const RETURN_OVERRIDE_JUSTIFICATION_REQUIRED = 'RETURN_OVERRIDE_JUSTIFICATION_REQUIRED';
export const RETURN_REPLACEMENT_NOT_CONFIGURED = 'RETURN_REPLACEMENT_NOT_CONFIGURED';
export const RETURN_REFUND_NOT_APPLICABLE = 'RETURN_REFUND_NOT_APPLICABLE';
export const RETURN_EVIDENCE_LIMIT_EXCEEDED = 'RETURN_EVIDENCE_LIMIT_EXCEEDED';

export const RETURN_CURRENCY = 'INR';

export const RETURN_SUBMITTED_CUSTOMER_MESSAGE =
  'Your return request has been submitted and is under review.';

/** Reason code that unlocks the expired-product exception path. */
export const EXPIRED_PRODUCT_REASON_CODE = 'EXPIRED_PRODUCT';

/** SLA badge thresholds, mirroring the refund-request module. */
export const RETURN_SLA_ORANGE_AFTER_HOURS = 48;
export const RETURN_SLA_RED_AFTER_HOURS = 96;

/**
 * A customer may still withdraw a request until operations commit to a pickup.
 * Once a pickup is scheduled the request must be cancelled by an admin.
 */
export const CUSTOMER_CANCELLABLE_STATUSES = [
  'REQUESTED',
  'UNDER_REVIEW',
  'ADDITIONAL_INFORMATION_REQUIRED',
  'APPROVED',
  'PICKUP_SCHEDULED',
  'PICKUP_ATTEMPTED',
] as const;

export const RETURN_MAX_EVIDENCE_FILES = 10;
